version: "3"
services:
  client:
    build: .
    container_name: client
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
  
  server:
    build: ../../Server
    container_name: server
    environment: 
        DB_CONNECTION_URL: mongodb://mongo:27017
        APPLICATION_PORT: 3003
    ports:
      - "3003:3003"
    depends_on: 
      - mongo

  mongo:
    image: mongo
    ports: 
      - "27017:27017"
